# Generated by Django 3.1.7 on 2021-04-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'permissions': (('can_join_group', 'Can join group'),)},
        ),
        migrations.AddField(
            model_name='deal',
            name='is_multi_use',
            field=models.BooleanField(default=False),
        ),
    ]
